import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Header from "@/components/header";
import { Separator } from "@/components/ui/separator";
import Providers from "@/providers";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(`max-w-screen-2xl mx-auto`, inter.className)}>
        <Providers>
          <Header />
          <Separator />
          <div>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
